### ISSUE TITLE
VuePress Migration Feedback

### ISSUE THREAD

**Issue by bencodezen** [translation-gang/ru.vuejs.org#467]
Hello! 

My name is Ben Hong and I'm a Vue.js Community Partner that is currently working with the Vue.js Core Docs Team to help with updating the platform from Hexo to VuePress. During this time, we plan to have a content freeze in order to ensure all of the sites stay in sync with one another.

As maintainers for the Russian translation site, are there any pain points or concerns that you might have about this migration? We would love to hear from you and make sure your thoughts are taken into consideration before starting work on this.

Looking forward to your response!

**Comment by gbezyuk** [comment]
Hello!I'm not fully sure I understand the platform update operation in all details, but as long as it deals only with the engine and not with the content, I guess translation team shouldn't have any objections.01.05.2019, 18:14, "Ben Hong" <notifications@github.com>:Hello!
My name is Ben Hong and I'm a Vue.js Community Partner that is currently working with the Vue.js Core Docs Team to help with updating the platform from Hexo to VuePress. During this time, we plan to have a content freeze in order to ensure all of the sites stay in sync with one another.
As maintainers for the Russian translation site, are there any pain points or concerns that you might have about this migration? We would love to hear from you and make sure your thoughts are taken into consideration before starting work on this.
Looking forward to your response!

**Comment by bencodezen** [comment]
Correct. It is only the engine.

We will reach out with more details when we have a formal content freeze date.

Thank you for the quick response!
